### PR TITLE
Interrupt sbt triggered mode

### PR DESCRIPTION
**Pull request by ashawley**
- Type `C-c C-b C-j` in ENSIME minor mode
- Type `C-c C-j` in sbt mode

Depends on:

- ~~ensime/ensime-emacs#601~~
- ~~ensime/emacs-sbt-mode#102~~

### CODE REVIEW

**Comment by fommil** [comment]
I would prefer that we recommend a (per project) buffer-save-hook for this to be honest. In either case, the sbt specific docs should go into the emacs-sbt page.

Did you explore using the hook approach? I think it would be useful to document it, even if you would prefer to use the inefficient sbt poller. We should document the inefficiencies, I thought we did but apparently not.

**Comment by ashawley** [comment]
> Did you explore using the hook approach? I think it would be useful to document it, even if you would prefer to use the inefficient sbt poller.

Sure, I'm on board with running commands explicitly (`C-c C-c c`, `C-c C-c a`, the various `ensime-sbt-do*` commands) and using save hooks.  I'm just trying to fix it for others, e.g. ensime/ensime-sbt#218.

> the sbt specific docs should go into the emacs-sbt page

Ah, ok.  I'll split that out.

**Comment by ashawley** [comment]
Ok, moved it from the Emacs user guide to sbt-mode page and added after "Cancelling processes" section on the sbt page, as well.

**Comment by fommil** [comment]
Thanks! Almost there, place remove Emacs references from the sbt plugin page, this definitely only belongs on the sbt-mode page (remember atom/vim/sublime users read this page)

**Comment by ashawley** [comment]
Ok, done!

**Pull request merged**
