### PR TITLE
instructions for development and troubleshooting

### PR DESCRIPTION
**Pull request by hedefalk**

### CODE REVIEW

**Comment by fommil** [comment]
cool! Can you also please add a link or some info to the "Contributing" page?

I'm in two minds about this. Do we put everything under there for each of the components, or do we put a contributing page under each of the client / build tool components and leave Contributing for the server?

**Comment by fommil** [comment]
also @hedefalk do you not need to nuke the coursier cache too? Or do you always do that anyway.

**Comment by fommil** [comment]
ok, I like have a developing / contributing page under the editor. We'll do that in Emacs as well and leave the top level Contributing page as a landing page and for server development only.

**Comment by hedefalk** [comment]
@fommil Yeah, you're right about coursier! I think I'm gonna remove sbt entirely and change that instruction to just nuke coursier cache. And I think I'm gonna remove the use of classpath files too since they seem to be an unnecessary indirection and just do in-mem classpaths. Without `-m update-changing` in coursier, the fetch is just seconds anyway if jar's are cached. And if problems you need to nuke the cache anyways, right? Might add a fetch command with `-m update-changing` called "update ensime server" again.

**Comment by fommil** [comment]
What about publish local?

**Comment by hedefalk** [comment]
@fommil Hm, I realize I'm not sure, maybe you could help me…

If I run coursier with `-m update changing` that will basically always guarantee latest SNAPSHOT of ensime right? Do I ever need to nuke the cache then? If I'm just "using" ensime?

**Comment by fommil** [comment]
And do you support the assembly jars?

**Comment by hedefalk** [comment]
Hm, yeah, if developing, that's a different story…

**Comment by fommil** [comment]
Definitely needs to be in the troubleshooting. People do it then forget.

**Comment by hedefalk** [comment]
What ARE the assembly jars? I'm just doing like your example? org.ensime % ensime.

https://github.com/hedefalk/ensime-node/blob/master/src/ensime-server-update-coursier.coffee#L55

**Comment by hedefalk** [comment]
@fommil Yeah, you're probably right. ensime-atom had a few reports that seems to be that they tried out ensime a year ago and now revisited. And some with installs in ivy local. But with coursier, how does that work? I only see maven as a repo in my own script:

 '-r', 'file:///$HOME/.m2/repository

If I did publishLocal on ivy, will that be picked up by my script?

**Comment by fommil** [comment]
I'm not sure, but i think coursier looks in there.

Look at the server installation instructions for Emacs to see what i mean about assembly jars.

**Pull request merged**
