### PR TITLE
Add instructions for launching the server manually for tests

### PR DESCRIPTION
**Pull request by iravid**
Added a short paragraph on launching the server directly from the project build and connecting to it from `ensime-emacs`.

### CODE REVIEW

**Comment by fommil** [comment]
cool, thanks for thinking about this and writing this up. However, our preference for QA testing is to build an assembly jar and emacs will then launch the server that way. By introducing a second method, we are confusing matters. For example, there is already another mechanism, `sbt publishLocal`, which we intentionally don't document for the same reason. Does that make sense?

**Comment by iravid** [comment]
Sure. I just found the approach of running ensime directly faster for debugging/testing functionality, compared to creating a jar (either by publishLocal or by assembly) and copying it to the specified directory.

**Comment by fommil** [comment]
you'll find subtle differences, such as the starting directory.

**Comment by iravid** [comment]
Ah, interesting, haven't run into that yet. Thanks for pointing out. I'll close this PR then.

**Comment by fommil** [comment]
thanks for sending it in and don't let it put you off sending more... it's a much higher quality discussion around a PR than a gitter chat :smile:

**Comment by iravid** [comment]
Sure - no worries! Thanks for the quick response :-)

**Pull request closed without merging**
