### PR TITLE
Attempting to inline edit button

### PR DESCRIPTION
**Pull request by Redrield**
I've done my best to address #18 and to inline the edit button on all pages, and to simply replace it and give an explanation on the homepage. It may have just been me, but I found that no matter what I did, the octocat image would be on a new line in the title.

### CODE REVIEW

**Comment by fommil** [comment]
Are you sure these extra bundles are available in github pages? I don't think they are.

**Comment by Redrield** [comment]
My bad, I didn't realize that the gemfile got changed. It won't affect the PR, so if it's possible to cut it out, do so. If not, I'll close this and redo the changed, but leave the gemfile out

**Comment by fommil** [comment]
Just push a commit to your PR branch with the changes backed out... I'll squash

**Comment by fommil** [comment]
Thanks!

**Comment by fommil** [comment]
Argh, still showing up with a newline for me (nexus 6)

**Comment by Redrield** [comment]
Like I said, I can't for the life of me get it on the same line as the title. I don't know what else to try

**Comment by fommil** [comment]
Hmm, well maybe we could just close the ticket as too much work... and you got a pr merged so it counts for octoberfest (i think)

**Pull request merged**
