### PR TITLE
Update troubleshooting.md to include a potentially necessary step aft…

### PR DESCRIPTION
**Pull request by Jacoby6000**
Update troubleshooting.md to include a potentially necessary step after deleting ensime from the ivy cache.

### CODE REVIEW

**Comment by Jacoby6000** [comment]
Added alternate email to my account. The CLA should clear soon.

**Comment by ChrisCoffey** [comment]
Do you mind squashing these? I've elaborated on the point in #105, but it can't hurt to repeat yourself in the troubleshooting section

**Comment by Jacoby6000** [comment]
Bah. I messed something up when squashing the commits.  If you could add the step to your branch that'd be fine.  I'm not sure how much it adds having it in two places, though.

**Comment by fommil** [comment]
There is no need to ask people to squash anymore because github added a really cool feature that lets us do it!

**Comment by fommil** [comment]
Yeah this branch is wrecked

**Pull request closed without merging**
