### PR TITLE
Hopefully clear up how to install for Scala 2.12

### PR DESCRIPTION
**Pull request by arigoldx**
We have be having lots of questions on Gitter about how to install for Scala 2.12 even though it's in the instructions. Hopefully this makes it clearer.

### CODE REVIEW

**Comment by fommil** [comment]
thanks!

**Comment by arigoldx** [comment]
thrilled to help, if even the teeniest bit

(been feeling like a punk for the past two weeks 'cause this triviality shoulda been done back then.. tho yeah, life.)

**Comment by arigoldx** [comment]
also, pardon the wording -- i thought i was copying your suggestion (nearly) literally :bowtie:

**Comment by fommil** [comment]
ha, nice, I never knew about the bowtie smiley

**Pull request merged**
