### PR TITLE
Updated typechecking commands to the correct values

### PR DESCRIPTION
**Pull request by noelmarkham**

### CODE REVIEW

**Comment by rorygraves** [comment]
Thanks @noelmarkham

**Comment by edani** [comment]
Actually should we pull the plug on ensime.github.io ? That doc was copied to the ensime-server wiki a while ago, and it's now out of date in several places.

**Comment by noelmarkham** [comment]
If my $0.02 is of any value, I found the doc very helpful to get going. If it just needs a bit of TLC then I'd like to see it kept. If I can help somehow I'd be happy to, but being very new to Ensime I don't know how much value I can add.

Cheers.

**Comment by edani** [comment]
The thing is, the more up-to-date version is here: https://github.com/ensime/ensime-server/wiki . We found that keeping the wiki updated was easier.

**Pull request merged**
