### PR TITLE
Fixes small typo

### PR DESCRIPTION
**Pull request by mgttlinger**

### CODE REVIEW

**Comment by fommil** [comment]
still wrong :stuck_out_tongue:

**Comment by mgttlinger** [comment]
Is it? The oxford dictionary spells it like that(https://en.oxforddictionaries.com/definition/customize). Or am I missing something else?

**Comment by fommil** [comment]
that must be the Oxford in Ameruca

**Comment by fommil** [comment]
:wink: merry xmas

**Comment by mgttlinger** [comment]
Thanks, I wish you the same.
About the 's' vs 'z' thing: I think I read somewhere that US-English uses 'z' exclusively while UK-English allows both but more or less moved to using 'z'.

**Pull request merged**
