### PR TITLE
Add resolver to installation lines

### PR DESCRIPTION
**Pull request by amirkarimi**
It didn't get the plugin (for me) without adding resolver.

### CODE REVIEW

**Comment by fommil** [comment]
Sorry, this in incorrect. It is on maven central.

**Comment by amirkarimi** [comment]
I had to add the resolver to be able to download the plugin!

**Comment by fommil** [comment]
Sounds like you have a problem with your setup, check that you are using maven central. It would not be appropriate to advise everybody to use snapshots for a released plugin, for security and performance reasons. You only need to add the resolver to follow along for snapshot releases.

**Comment by amirkarimi** [comment]
Thanks for explanation.

**Pull request closed without merging**
