### PR TITLE
Build tool page tweaks

### PR DESCRIPTION
**Pull request by dwijnand**
"sbt" over "SBT" and avoid showing CBT like it's a broken link.

image

Also (I think I mentioned it you) on my first consumption of this page I didn't see the "Learn more →" header, so didn't know how to proceed. Perhaps enumerating (and hyperlinking) to the relevant build tools doc pages could be done first, and then feature comparison matrix could come below it.

### CODE REVIEW

**Comment by dwijnand** [comment]
wow that CI is fast "Elapsed time 1 min 58 sec"

**Comment by fommil** [comment]
I keep hoping somebody will just turn the header images into the links for the webpages. I can't see the visual effect of this edit, so fingers crossed!

**Comment by dwijnand** [comment]
image

hmm not centred for some reason..

**Comment by fommil** [comment]
Hmm. Yeah I like the idea about having the list of links first, then the feature matrix. Same for the editors.

**Comment by dwijnand** [comment]
I'll give it a (time-boxed) shot.

**Pull request merged**
